'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {ThemeProvider} from "@mui/material";
import theme from "./theme";
import {Nav} from "./components/Nav";
import React from "react";
import { QueryClientProvider} from "@tanstack/react-query";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import {queryClient} from "@/app/hooks/queryClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [qClient] = React.useState(() => queryClient);
  return (

    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <QueryClientProvider client={qClient}>
          <ReactQueryDevtools initialIsOpen={false} />

        <section>
          <Nav />

          {children}
        </section>

        </QueryClientProvider>
      </ThemeProvider>
    </AppRouterCacheProvider>
  </body>
    </html>
  );
}
